.TH "arping" "8" "12th Feb, 2002" "arping" "" 
.PP 
.SH "NAME" 
arping \- sends arp and/or ip pings to a given host
.PP 
.SH "SYNOPSIS" 
\fBarping\fP [-hqavrRd0bp] [-S \fIhost/ip\fP] [-T \fIhost/ip\fP] [-s \fIMAC\fP]    [-t \fIMAC\fP] [-c \fIcount\fP] [-i \fIinterface\fP] <\fIhost\fP | -B>
.PP 
.SH "DESCRIPTION" 
The \fIarping\fP utility sends \fBARP\fP and/or \fBICMP\fP requests to the specified \fIhost\fP and displays the replies\&. The \fIhost\fP may be specified by its \fBhostname\fP, its \fBIP\fP address, or its \fBMAC\fP address\&.
.PP 
One request is sent each second\&.
.PP 
\fIImportant note on timing\fP
.PP 
ARP packets are usually replied to (on a LAN) so fast that the OS task
scheduler can\&'t keep up to get exact enough timing\&.
On an idle system the roundtrip times will be pretty much accurate, but
with more load the timing gets less exact\&.
.PP 
To get more exact timing on a non-idle system, re-nice arping to -15 or so\&.
.PP 
# nice -n -15 arping foobar
.PP 
This is not just an issue with arping, it is with normal ping also
(at least it is on my system)\&. But it doesn\&'t show up as much with ping
since arping packets (when pinging IP) doesn\&'t traverse the IP stack when
received and are therefore replied to faster\&.
.PP 
.SH "OPTIONS" 
.PP 
.IP 
.IP "-h" 
Displays a help message and exits\&.
.IP "-q" 
Does not display messages, except error messages\&.
.IP "-a" 
Audiable ping\&.
.IP "-v" 
Verbose output\&. Use twice for more messages\&.
.IP "-r" 
Raw output: only the MAC/IP address is displayed for each reply\&.
.IP "-R" 
Raw output: Like -r but shows "the other one", can be combined with
-r\&.
.IP "-d" 
Find duplicate replies\&.
.IP "-B" 
Use instead of host if you want to address 255\&.255\&.255\&.255\&.
.IP "-0" 
Use this option to ping with source IP address 0\&.0\&.0\&.0\&. Use this
when you haven\&'t configured your interface yet\&.
Note that this may get the MAC-ping unanswered\&.
This is an alias for -S 0\&.0\&.0\&.0\&.
.IP "-b" 
Like -0 but source broadcast source address (255\&.255\&.255\&.255)\&.
Note that this may get the arping unanswered since it\&'s not normal behavior
for a host\&.
.IP "-S \fIIP\fP" 
Like -b and -0 but with set source address\&.
Note that this may get the arping unanswered if the target does not have
routing to the IP\&. If you don\&'t own the IP you are using, you may need to turn
on promiscious mode on the interface (with -p)\&. With this switch you can find
out what IP-address a host has without taking an IP-address yourself\&.
.IP "-T \fIIP\fP" 
Use -T as target address when pinging MACs that won\&'t
respond to a broadcast ping but perhaps to a directed broadcast\&.
.IP 
\fIExample\fP:                                                                To check the address of MAC-A, use knowledge of MAC-B and IP-B\&.
.IP 
$ arping -S <IP-B> -s <MAC-B> -p <MAC-A>
.IP "-p" 
Turn on promiscious mode on interface, use this if you don\&'t
"own" the MAC address you are using\&.
.IP "-s \fIMAC\fP" 
Set source MAC address\&. You may need to use -p with this\&.
.IP "-t \fIMAC\fP" 
Set target MAC address to use when pinging IP address\&.
.IP "-c \fIcount\fP" 
Only send \fIcount\fP requests\&.
.IP "-i \fIinterface\fP" 
Use the specified interface\&.
.PP 
.SH "BUGS" 
.PP 
You have to use -B instead of arpinging 255\&.255\&.255\&.255, and -b
instead of -S 255\&.255\&.255\&.255\&. This is libnets fault\&.
.PP 
.SH "SEE ALSO" 
.PP 
\fBping(8)\fP, \fBarp(8)\fP, \fBrarp(8)\fP
.PP 
.SH "AUTHOR" 
.PP 
Arping was written by Thomas Habets <thomas@habets\&.pp\&.se> aka
<marvin@rootbusters\&.net>
